#cloud-config

coreos:
  units:
    - name: install-kube.service
      content: |
        [Unit]
        Wants=network-online.target
        After=network-online.target

        [Service]
        RemainAfterExit=yes
        ExecStartPre=-/usr/bin/mkdir -p /opt/bin/
        ExecStartPre=-/usr/bin/wget "${KUBELET_URL}" -O /opt/bin/kubelet
        ExecStartPre=-/usr/bin/wget "${HYPERKUBE_URL}" -O /opt/bin/hyperkube
        ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet
        ExecStartPre=/usr/bin/chmod +x /opt/bin/hyperkube
        ExecStart=/bin/true
        ExecStop=/bin/true
        Type=oneshot

        [Install]
        WantedBy=multi-user.target
      command: start
